import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import SiteHeader from '@/components/SiteHeader';
import { ArrowRight, BookOpen, Heart, Package, UserRound } from 'lucide-react';
import { editorialEntries, formatPrice, products } from '@/lib/brand';
import { getSavedArticles, SAVED_ARTICLES_UPDATED_EVENT } from '@/lib/store';

export default function Account() {
  const [savedSlugs, setSavedSlugs] = useState<string[]>(() => getSavedArticles());
  useEffect(() => {
    const syncSavedArticles = () => setSavedSlugs(getSavedArticles());
    window.addEventListener(SAVED_ARTICLES_UPDATED_EVENT, syncSavedArticles);
    return () => window.removeEventListener(SAVED_ARTICLES_UPDATED_EVENT, syncSavedArticles);
  }, []);
  const savedArticles = savedSlugs.map(slug => editorialEntries.find(entry => entry.slug === slug)).filter(Boolean);

  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><SiteHeader /><main className="container py-12 md:py-20">
    <div className="flex flex-col justify-between gap-4 border-b border-[#D7C2A7] pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#866F62]">Welcome back</p><h1 className="mt-3 font-display text-5xl">Your account</h1></div><button className="text-[10px] uppercase tracking-[.15em] underline">Sign in / Create account</button></div>
    <div className="mt-10 grid gap-5 sm:grid-cols-3"><div className="bg-[#D7C2A7] p-6"><Package size={19} strokeWidth={1.3}/><p className="mt-7 text-[10px] uppercase tracking-[.15em] text-[#866F62]">Recent orders</p><p className="mt-2 font-display text-3xl">2</p></div><div className="bg-[#D7C2A7] p-6"><Heart size={19} strokeWidth={1.3}/><p className="mt-7 text-[10px] uppercase tracking-[.15em] text-[#866F62]">Wishlist</p><p className="mt-2 font-display text-3xl">4</p></div><div className="bg-[#382820] p-6 text-white"><UserRound size={19} strokeWidth={1.3}/><p className="mt-7 text-[10px] uppercase tracking-[.15em] text-[#D7C2A7]">Account status</p><p className="mt-2 font-display text-3xl">Active</p></div></div>
    <div className="mt-12 grid gap-12 lg:grid-cols-[1.2fr_.8fr]"><section><div className="flex items-center justify-between border-b border-[#D7C2A7] pb-4"><h2 className="font-display text-3xl">Recent orders</h2><button className="text-[10px] uppercase tracking-[.15em]">View all</button></div><div className="divide-y divide-[#D7C2A7]"><div className="flex items-center justify-between gap-4 py-6"><div><p className="text-sm">#AV-10284</p><p className="mt-2 text-xs text-[#866F62]">04 February 2026 · 2 items</p></div><div className="text-right"><p className="text-sm">{formatPrice(216000)}</p><p className="mt-2 text-xs text-[#B7654A]">Processing</p></div><ArrowRight size={16}/></div><div className="flex items-center justify-between gap-4 py-6"><div><p className="text-sm">#AV-10177</p><p className="mt-2 text-xs text-[#866F62]">18 January 2026 · 1 item</p></div><div className="text-right"><p className="text-sm">{formatPrice(124000)}</p><p className="mt-2 text-xs text-[#866F62]">Delivered</p></div><ArrowRight size={16}/></div></div></section><aside><div className="flex items-center justify-between border-b border-[#D7C2A7] pb-4"><h2 className="font-display text-3xl">Wishlist</h2><Link href="/shop" className="text-[10px] uppercase tracking-[.15em]">Explore</Link></div><div className="mt-5 grid grid-cols-2 gap-4">{products.slice(1,3).map(p=><Link key={p.id} href={`/product/${p.id}`}><img src={p.image} alt={p.name} className="aspect-[4/5] w-full object-cover"/><p className="mt-3 text-xs">{p.name}</p></Link>)}</div></aside></div>
    <section className="mt-16 border-t border-[#D7C2A7] pt-10" aria-labelledby="saved-articles-heading"><div className="flex flex-col justify-between gap-4 border-b border-[#D7C2A7] pb-4 sm:flex-row sm:items-end"><div><p className="eyebrow text-[#B7654A]">Your reading list</p><h2 id="saved-articles-heading" className="mt-3 font-display text-3xl md:text-4xl">Saved Articles</h2></div><Link href="/edit" className="inline-flex items-center gap-2 text-[10px] uppercase tracking-[.15em]">Explore The Edit <ArrowRight size={14} /></Link></div>{savedArticles.length === 0 ? <div className="flex flex-col items-start gap-4 py-10"><BookOpen size={22} strokeWidth={1.3} /><p className="max-w-md text-sm leading-7 text-[#866F62]">Save stories from The Áveraẹ Edit and they will stay here for your next moment of inspiration.</p><Link href="/edit" className="action-link-light inline-flex items-center gap-2 bg-[#382820] px-4 py-3 text-[10px] uppercase tracking-[.15em]">READ THE EDIT <ArrowRight size={14} /></Link></div> : <div className="mt-7 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">{savedArticles.map(entry => <Link key={entry!.slug} href={`/edit/${entry!.slug}`} className="group block"><div className="aspect-[4/3] overflow-hidden bg-[#D7C2A7]"><img src={entry!.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /></div><p className="mt-4 text-[10px] uppercase tracking-[.15em] text-[#B7654A]">{entry!.category} · {entry!.readingTime}</p><h3 className="mt-2 font-display text-2xl leading-tight group-hover:underline">{entry!.title}</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">{entry!.description}</p></Link>)}</div>}</section>
  </main></div>;
}
