import { ArrowRight, Check, Clock3, MapPin, Package, Truck } from 'lucide-react';
import { Link } from 'wouter';
import SiteHeader from '@/components/SiteHeader';
import BackToTop from '@/components/BackToTop';
import SupportLinks from '@/components/SupportLinks';

const deliveryOptions = [
  { title: 'Standard Delivery', detail: 'Reliable delivery for everyday orders.', timing: '3–5 working days', cost: 'From ₦3,500' },
  { title: 'Express Delivery', detail: 'A faster option for time-sensitive orders.', timing: '1–2 working days', cost: 'From ₦7,500' },
  { title: 'Same-Day Delivery', detail: 'Available for selected Lagos addresses and eligible orders placed before midday.', timing: 'Same day', cost: 'Calculated at checkout' },
  { title: 'Store Pickup', detail: 'Collect from our Lagos studio when this option is available at checkout.', timing: 'Ready within 1 working day', cost: 'Free' },
];

const areas = ['Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Benin City', 'Enugu', 'Kano'];

export default function Delivery() {
  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><SiteHeader /><main>
    <section className="border-b border-[#D7C2A7] bg-[#FFFDF8]"><div className="container py-14 md:py-20"><nav aria-label="Breadcrumb" className="text-[10px] uppercase tracking-[.14em] text-[#866F62]"><Link href="/" className="hover:text-[#B7654A]">Home</Link><span className="mx-2">/</span><span aria-current="page">Delivery</span></nav><div className="mt-10 max-w-2xl"><p className="eyebrow text-[#B7654A]">Delivery, considered</p><h1 className="mt-3 font-display text-5xl md:text-7xl">Delivery Information</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[#866F62]">Everything you need to know about getting your Áveraẹ order to you.</p></div></div></section>
    <section className="container py-14 md:py-20"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr]"><aside><p className="eyebrow text-[#B7654A]">Delivery options</p><h2 className="mt-3 font-display text-3xl md:text-4xl">Choose what suits you</h2><p className="mt-4 max-w-sm text-sm leading-7 text-[#866F62]">Your available options and final delivery fee are confirmed at checkout based on your address, order, and timing.</p><div className="mt-8 space-y-4"><Link href="/account#orders" className="inline-flex items-center gap-2 bg-[#382820] px-5 py-3 text-[10px] uppercase tracking-[.15em] text-[#FFFDF8] transition hover:bg-[#B7654A]">TRACK YOUR ORDER <ArrowRight size={14} /></Link><Link href="/contact" className="ml-3 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.15em] underline underline-offset-4">CONTACT US <ArrowRight size={14} /></Link><SupportLinks className="mt-6" includeFaq includeSizeGuide label="More help" /></div></aside><div className="grid gap-4 sm:grid-cols-2">{deliveryOptions.map(option => <article key={option.title} className="border border-[#D7C2A7] bg-[#FFFDF8]/55 p-5"><Truck size={19} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-7 font-display text-2xl">{option.title}</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">{option.detail}</p><div className="mt-6 border-t border-[#D7C2A7] pt-4 text-xs"><p><span className="text-[#866F62]">Estimated time</span><br /><span className="mt-1 inline-block">{option.timing}</span></p><p className="mt-3"><span className="text-[#866F62]">Delivery cost</span><br /><span className="mt-1 inline-block">{option.cost}</span></p></div></article>)}</div></div></section>
    <section className="border-y border-[#D7C2A7] bg-[#FFFDF8] py-14 md:py-20"><div className="container"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#B7654A]">Timing and costs</p><h2 className="mt-3 font-display text-3xl md:text-4xl">What to expect</h2><p className="mt-4 max-w-md text-sm leading-7 text-[#866F62]">Orders are prepared with care, then handed to our delivery partners. Delivery estimates begin after dispatch, not when the order is placed.</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="border-l border-[#B7654A] pl-5"><Clock3 size={18} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-5 text-sm">Order processing</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">Most orders are processed within 1–2 working days. Personalised or made-to-order pieces may take longer; any additional timing is shown at checkout.</p></div><div className="border-l border-[#B7654A] pl-5"><Package size={18} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-5 text-sm">Free delivery</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">Standard delivery is free on orders over ₦150,000. Express, same-day, and location-based charges may still apply.</p></div><div className="border-l border-[#B7654A] pl-5"><Check size={18} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-5 text-sm">Tracking</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">When your order is dispatched, we send tracking details to the email address used at checkout.</p></div><div className="border-l border-[#B7654A] pl-5"><MapPin size={18} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-5 text-sm">Delivery areas</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">We currently serve selected locations across Nigeria. Enter your address at checkout to confirm availability.</p></div></div></div></div></section>
    <section className="container py-14 md:py-20"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#B7654A]">Where we deliver</p><h2 className="mt-3 font-display text-3xl md:text-4xl">Delivery areas</h2><p className="mt-4 text-sm leading-7 text-[#866F62]">Availability can vary by postcode and service level. The checkout address checker is the most accurate way to confirm your location.</p><div className="mt-6 flex flex-wrap gap-2">{areas.map(area => <span key={area} className="border border-[#D7C2A7] px-3 py-2 text-[10px] uppercase tracking-[.12em]">{area}</span>)}</div></div><div className="space-y-3"><details className="group border border-[#D7C2A7] bg-[#FFFDF8]/55 p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm"><span>Important information about delays</span><span className="text-xl font-light transition group-open:rotate-45">+</span></summary><div className="mt-4 space-y-3 text-sm leading-6 text-[#866F62]"><p>Public holidays, severe weather, courier disruption, high order volumes, and remote-area routing can extend delivery estimates.</p><p>We will share material changes to your delivery timing through the contact details on your order.</p></div></details><details className="group border border-[#D7C2A7] bg-[#FFFDF8]/55 p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm"><span>I entered the wrong delivery information</span><span className="text-xl font-light transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-6 text-[#866F62]">Contact us as soon as possible with your order number. If the order has not been dispatched, we will do our best to update the address. Once dispatched, changes may not be possible.</p></details><details className="group border border-[#D7C2A7] bg-[#FFFDF8]/55 p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm"><span>What happens if I miss my delivery?</span><span className="text-xl font-light transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-6 text-[#866F62]">The courier may attempt redelivery or contact you to arrange a suitable time. Please use your tracking details or contact our team if you need help.</p></details></div></div></section>
    <section className="bg-[#382820] py-14 text-[#FFFDF8] md:py-16"><div className="container flex flex-col items-start justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow text-[#D7C2A7]">Need a hand?</p><h2 className="mt-3 font-display text-3xl">We are here to help with your delivery.</h2></div><Link href="/contact" className="inline-flex items-center gap-2 bg-[#B7654A] px-5 py-3 text-[10px] uppercase tracking-[.15em] text-[#FFFDF8] transition hover:bg-[#FFFDF8] hover:text-[#382820]">CONTACT US <ArrowRight size={14} /></Link></div></section>
  </main><BackToTop /></div>;
}
