import { ArrowRight } from 'lucide-react';
import { Link } from 'wouter';
import { brand, editorialEntries, formatPrice, products, trendItems } from '@/lib/brand';

export function Trends() {
  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><div className="border-b border-[#D7C2A7] px-5 py-5"><div className="container flex items-center justify-between"><Link href="/" className="font-display text-2xl tracking-[.16em]">{brand.name}</Link><Link href="/shop" className="text-[10px] uppercase tracking-[.16em]">Shop all</Link></div></div><main className="container py-16 md:py-24"><p className="eyebrow text-[#B7654A]">Discover what’s relevant now</p><h1 className="mt-4 max-w-2xl font-display text-6xl leading-none md:text-8xl">Trending now.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#866F62]">Browse the styles, products and ideas shaping the next expression of fashion.</p><div className="mt-16 grid gap-8 md:grid-cols-3">{trendItems.map(item => <article key={item.title} className="border-t border-[#D7C2A7] pt-5"><span className="text-[10px] uppercase tracking-[.16em] text-[#B7654A]">{item.label}</span><h2 className="mt-12 font-display text-4xl">{item.title}</h2><p className="mt-4 text-sm leading-7 text-[#866F62]">{item.description}</p><Link href={`/product/${item.productId}`} className="mt-8 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.16em]">View product <ArrowRight size={14} /></Link></article>)}</div><section className="mt-24 border-t border-[#D7C2A7] pt-8"><div className="flex items-end justify-between"><div><p className="eyebrow text-[#866F62]">Popular products</p><h2 className="mt-3 font-display text-4xl">The pieces people are finding now</h2></div><Link href="/shop" className="text-[10px] uppercase tracking-[.16em]">Shop all</Link></div><div className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map(product => <Link key={product.id} href={`/product/${product.id}`} className="group"><div className="aspect-[4/5] overflow-hidden bg-[#D7C2A7]"><img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /></div><span className="mt-4 block text-[10px] uppercase tracking-[.15em] text-[#B7654A]">Trending</span><div className="mt-1 flex justify-between gap-4 text-sm"><span>{product.name}</span><span>{formatPrice(product.price)}</span></div></Link>)}</div></section></main></div>;
}

export function Edit() {
  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><div className="border-b border-[#D7C2A7] px-5 py-5"><div className="container flex items-center justify-between"><Link href="/" className="font-display text-2xl tracking-[.16em]">{brand.name}</Link><Link href="/shop" className="text-[10px] uppercase tracking-[.16em]">Shop all</Link></div></div><main className="container py-16 md:py-24"><p className="eyebrow text-[#B7654A]">Stories, style and culture</p><h1 className="mt-4 max-w-3xl font-display text-6xl leading-none md:text-8xl">The {brand.name} Edit.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-[#866F62]">Fashion trends, style guides, cultural spotlights and the ideas behind the pieces worth finding.</p><div className="mt-16 grid gap-10 md:grid-cols-3">{editorialEntries.map(entry => <Link key={entry.slug} href={`/edit/${entry.slug}`} className="group"><div className="aspect-[4/3] overflow-hidden bg-[#D7C2A7]"><img src={entry.image} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /></div><span className="mt-5 block text-[10px] uppercase tracking-[.15em] text-[#B7654A]">{entry.label}</span><h2 className="mt-2 font-display text-3xl group-hover:underline">{entry.title}</h2><p className="mt-3 text-sm leading-7 text-[#866F62]">{entry.description}</p><span className="mt-5 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.16em]">READ ARTICLE <ArrowRight size={14} /></span></Link>)}</div></main></div>;
}

export function EditArticle({ params }: { params: { slug: string } }) {
  const entry = editorialEntries.find(item => item.slug === params.slug) ?? editorialEntries[0];
  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><div className="border-b border-[#D7C2A7] px-5 py-5"><div className="container flex items-center justify-between"><Link href="/" className="font-display text-2xl tracking-[.16em]">{brand.name}</Link><Link href="/shop" className="text-[10px] uppercase tracking-[.16em]">Shop all</Link></div></div><main><div className="container py-16 md:py-24"><p className="eyebrow text-[#B7654A]">{entry.label}</p><h1 className="mt-4 max-w-4xl font-display text-6xl leading-none md:text-8xl">{entry.title}</h1><p className="mt-7 max-w-xl text-base leading-8 text-[#866F62]">{entry.description}</p></div><div className="aspect-[16/7] overflow-hidden bg-[#D7C2A7]"><img src={entry.image} alt="" className="h-full w-full object-cover" /></div><div className="container grid gap-12 py-16 md:grid-cols-[.7fr_1.3fr] md:py-24"><p className="eyebrow text-[#B7654A]">The story</p><div className="max-w-2xl text-base leading-9"><p>Style is a conversation between where we are and where we are going. This edit brings together pieces, proportions and perspectives that feel relevant now, while leaving room for personal expression.</p><p className="mt-7">Explore the products referenced in the story, then make the look your own.</p><Link href="/shop" className="mt-8 inline-flex items-center gap-2 border-b border-[#382820] pb-2 text-[10px] uppercase tracking-[.16em]">Shop the look <ArrowRight size={15} /></Link></div></div></main></div>;
}
