import { ArrowRight, Check, CircleAlert, Package, RefreshCw } from 'lucide-react';
import { Link } from 'wouter';
import SiteHeader from '@/components/SiteHeader';
import BackToTop from '@/components/BackToTop';

const returnSteps = [
  ['01', 'Log into your account.', 'Use the account area connected to the email address used for your purchase.'],
  ['02', 'Open My Orders.', 'Find the order containing the piece you would like to return.'],
  ['03', 'Select the relevant order.', 'Review the order details and identify the item you want to send back.'],
  ['04', 'Select REQUEST RETURN.', 'Choose the item and reason for return when the option is available.'],
  ['05', 'Follow the instructions.', 'Complete the return instructions shown for your order and location.'],
];

const conditions = ['The item must be unused and unworn.', 'The item must be in its original condition.', 'Original packaging should be included where applicable.', 'All tags should remain attached where required.'];

export default function Returns() {
  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><SiteHeader /><main>
    <section className="border-b border-[#D7C2A7] bg-[#FFFDF8]"><div className="container py-14 md:py-20"><nav aria-label="Breadcrumb" className="text-[10px] uppercase tracking-[.14em] text-[#866F62]"><Link href="/" className="hover:text-[#B7654A]">Home</Link><span className="mx-2">/</span><span aria-current="page">Returns &amp; Refunds</span></nav><div className="mt-10 max-w-2xl"><p className="eyebrow text-[#B7654A]">After your order</p><h1 className="mt-3 font-display text-5xl md:text-7xl">Returns &amp; Refunds</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[#866F62]">Changed your mind? Here's everything you need to know about returns and refunds.</p></div></div></section>
    <section className="container grid gap-12 py-14 md:py-20 lg:grid-cols-[.72fr_1.28fr]"><aside><p className="eyebrow text-[#B7654A]">Return policy</p><h2 className="mt-3 font-display text-3xl md:text-4xl">A clear way back</h2><p className="mt-4 max-w-sm text-sm leading-7 text-[#866F62]">You can request a return within 14 days of receiving your order. Items must meet the return conditions below so we can process them fairly and safely.</p><div className="mt-8 space-y-3"><Link href="/account#orders" className="inline-flex items-center gap-2 bg-[#382820] px-5 py-3 text-[10px] uppercase tracking-[.15em] text-[#FFFDF8] transition hover:bg-[#B7654A]">START FROM MY ORDERS <ArrowRight size={14} /></Link><Link href="/contact" className="ml-3 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.15em] underline underline-offset-4">CONTACT SUPPORT <ArrowRight size={14} /></Link></div></aside><div className="grid gap-5 sm:grid-cols-2"><div className="border border-[#D7C2A7] bg-[#FFFDF8]/55 p-6"><Check size={19} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-7 font-display text-2xl">Return conditions</h3><ul className="mt-5 space-y-3 text-sm leading-6 text-[#866F62]">{conditions.map(condition => <li key={condition} className="flex gap-3"><span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[#B7654A]" />{condition}</li>)}</ul></div><div className="border border-[#D7C2A7] bg-[#FFFDF8]/55 p-6"><CircleAlert size={19} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-7 font-display text-2xl">Non-returnable items</h3><p className="mt-4 text-sm leading-6 text-[#866F62]">For hygiene and safety, beauty, pierced jewellery, personalised pieces, and items marked final sale may not be eligible for return. Product-specific exclusions are shown on the relevant product page or at checkout.</p></div></div></section>
    <section className="border-y border-[#D7C2A7] bg-[#FFFDF8] py-14 md:py-20"><div className="container"><div className="max-w-xl"><p className="eyebrow text-[#B7654A]">How to start a return</p><h2 className="mt-3 font-display text-3xl md:text-4xl">Five considered steps</h2><p className="mt-4 text-sm leading-7 text-[#866F62]">Our current account flow may not support automated return requests for every order. If REQUEST RETURN is not shown, use CONTACT SUPPORT and include your order number.</p></div><div className="mt-10 grid gap-px overflow-hidden border border-[#D7C2A7] bg-[#D7C2A7] md:grid-cols-5">{returnSteps.map(([number, title, detail]) => <article key={number} className="bg-[#FFFDF8] p-5"><p className="font-display text-3xl text-[#B7654A]">{number}</p><h3 className="mt-8 text-sm leading-5">{title}</h3><p className="mt-3 text-xs leading-5 text-[#866F62]">{detail}</p></article>)}</div><div className="mt-7 border-l border-[#B7654A] pl-5"><p className="text-sm">Need help starting a return?</p><Link href="/contact" className="mt-2 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.14em] underline underline-offset-4">CONTACT SUPPORT <ArrowRight size={14} /></Link></div></div></section>
    <section className="container py-14 md:py-20"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow text-[#B7654A]">Refunds and exchanges</p><h2 className="mt-3 font-display text-3xl md:text-4xl">What happens next?</h2><p className="mt-4 max-w-md text-sm leading-7 text-[#866F62]">Once a returned item has been received and approved, we begin the refund process and keep the original payment route in view.</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="border-l border-[#B7654A] pl-5"><RefreshCw size={18} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-5 text-sm">Refund timing</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">Refunds are initiated after the returned item is received and checked. Allow 5–10 working days for the amount to appear, depending on your bank or payment provider.</p></div><div className="border-l border-[#B7654A] pl-5"><Package size={18} strokeWidth={1.3} className="text-[#B7654A]" /><h3 className="mt-5 text-sm">Original payment method</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">Approved refunds are sent to the original payment method. Bank or payment-provider processing delays may affect when the credit becomes visible.</p></div><div className="border-l border-[#B7654A] pl-5 sm:col-span-2"><h3 className="text-sm">Exchanges</h3><p className="mt-2 text-sm leading-6 text-[#866F62]">Direct exchanges depend on stock and are not available for every order. Contact support with your order number and preferred replacement; our team will explain the available options.</p></div></div></div></section>
    <section className="border-y border-[#D7C2A7] bg-[#FFFDF8] py-14 md:py-20"><div className="container grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-[#B7654A]">When something is not right</p><h2 className="mt-3 font-display text-3xl md:text-4xl">Damaged or incorrect items</h2><p className="mt-4 text-sm leading-7 text-[#866F62]">If your item arrives damaged, incorrect, or incomplete, please contact us as soon as possible with your order number and clear photographs of the item and packaging. Keep the item and packaging until our team advises you what to do next.</p><Link href="/contact" className="mt-6 inline-flex items-center gap-2 bg-[#382820] px-5 py-3 text-[10px] uppercase tracking-[.15em] text-[#FFFDF8] transition hover:bg-[#B7654A]">CONTACT US <ArrowRight size={14} /></Link></div><div className="space-y-3"><details className="group border border-[#D7C2A7] p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm"><span>Can I return a sale item?</span><span className="text-xl font-light transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-6 text-[#866F62]">Sale items may have specific return conditions. Check the product page or contact support before sending an item back.</p></details><details className="group border border-[#D7C2A7] p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm"><span>Who pays for return delivery?</span><span className="text-xl font-light transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-6 text-[#866F62]">Return delivery arrangements can vary by reason and location. Support will confirm the next step when your request is reviewed.</p></details><details className="group border border-[#D7C2A7] p-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-sm"><span>Looking for a quick answer?</span><span className="text-xl font-light transition group-open:rotate-45">+</span></summary><p className="mt-4 text-sm leading-6 text-[#866F62]">Visit the FAQ section on our Contact page for delivery, order, and product questions.</p><Link href="/contact#faqs" className="mt-3 inline-flex items-center gap-2 text-[10px] uppercase tracking-[.14em] underline underline-offset-4">VIEW FAQs <ArrowRight size={14} /></Link></details></div></div></section>
  </main><BackToTop /></div>;
}
