import { ArrowRight, Ruler } from 'lucide-react';
import { Link } from 'wouter';
import SiteHeader from '@/components/SiteHeader';
import BackToTop from '@/components/BackToTop';
import { brand } from '@/lib/brand';

const clothingRows = [
  ['XS', '82–86', '64–68', '88–92'],
  ['S', '86–90', '68–72', '92–96'],
  ['M', '90–96', '72–78', '96–102'],
  ['L', '96–102', '78–84', '102–108'],
  ['XL', '102–108', '84–90', '108–114'],
];

const footwearRows = [
  ['36', '23.0'], ['37', '23.7'], ['38', '24.3'], ['39', '25.0'], ['40', '25.7'], ['41', '26.3'], ['42', '27.0'],
];

export default function SizeGuide() {
  return <div className="min-h-screen bg-[#F6F0E6] text-[#382820]"><SiteHeader /><main>
    <section className="border-b border-[#D7C2A7] bg-[#FFFDF8]"><div className="container py-14 md:py-20"><nav aria-label="Breadcrumb" className="text-[10px] uppercase tracking-[.14em] text-[#866F62]"><Link href="/" className="transition hover:text-[#B7654A]">Home</Link><span className="mx-2">/</span><span aria-current="page">Size Guide</span></nav><div className="mt-10 max-w-2xl"><p className="eyebrow text-[#B7654A]">Fit, clearly considered</p><h1 className="mt-3 font-display text-5xl md:text-7xl">Size Guide</h1><p className="mt-5 max-w-xl text-sm leading-7 text-[#866F62]">Find your best Áveraẹ fit with simple measurement guidance for clothing and footwear.</p></div></div></section>
    <section className="container grid gap-12 py-14 md:py-20 lg:grid-cols-[1fr_.32fr]"><div className="space-y-12">
      <section><div className="flex items-center gap-3"><Ruler size={20} className="text-[#B7654A]" aria-hidden="true" /><div><p className="eyebrow text-[#B7654A]">Before you measure</p><h2 className="mt-2 font-display text-3xl">How to measure</h2></div></div><p className="mt-5 max-w-2xl text-sm leading-7 text-[#866F62]">Use a soft tape measure and keep it close to the body without pulling tight. Measure in centimetres while wearing light clothing, and compare your measurements with the product-specific notes on each page.</p><div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Bust / chest','Measure around the fullest point.'],['Waist','Measure the narrowest point.'],['Hips','Measure around the fullest point.']].map(([title, copy]) => <div key={title} className="border border-[#D7C2A7] bg-[#FFFDF8] p-5"><p className="text-sm font-medium">{title}</p><p className="mt-2 text-sm leading-6 text-[#866F62]">{copy}</p></div>)}</div></section>
      <section><p className="eyebrow text-[#B7654A]">Clothing</p><h2 className="mt-2 font-display text-3xl">Body measurements</h2><div className="mt-5 overflow-x-auto border border-[#D7C2A7] bg-[#FFFDF8]"><table className="w-full min-w-[520px] text-left text-sm"><caption className="sr-only">Clothing size measurements in centimetres</caption><thead className="border-b border-[#D7C2A7] text-[10px] uppercase tracking-[.12em] text-[#866F62]"><tr><th className="px-4 py-4 font-normal">Size</th><th className="px-4 py-4 font-normal">Bust / chest</th><th className="px-4 py-4 font-normal">Waist</th><th className="px-4 py-4 font-normal">Hips</th></tr></thead><tbody>{clothingRows.map(row => <tr key={row[0]} className="border-b border-[#E6D8C8] last:border-0"><th className="px-4 py-4 font-medium">{row[0]}</th>{row.slice(1).map(value => <td key={value} className="px-4 py-4 text-[#866F62]">{value} cm</td>)}</tr>)}</tbody></table></div><p className="mt-4 text-xs leading-6 text-[#866F62]">If you are between sizes, choose the larger size for a relaxed fit. Product pages may include additional garment measurements and fit notes.</p></section>
      <section><p className="eyebrow text-[#B7654A]">Footwear</p><h2 className="mt-2 font-display text-3xl">Foot length</h2><div className="mt-5 overflow-x-auto border border-[#D7C2A7] bg-[#FFFDF8]"><table className="w-full min-w-[360px] text-left text-sm"><caption className="sr-only">Footwear size measurements in centimetres</caption><thead className="border-b border-[#D7C2A7] text-[10px] uppercase tracking-[.12em] text-[#866F62]"><tr><th className="px-4 py-4 font-normal">EU size</th><th className="px-4 py-4 font-normal">Foot length</th></tr></thead><tbody>{footwearRows.map(row => <tr key={row[0]} className="border-b border-[#E6D8C8] last:border-0"><th className="px-4 py-4 font-medium">{row[0]}</th><td className="px-4 py-4 text-[#866F62]">{row[1]} cm</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-6 text-[#866F62]">Measure both feet at the end of the day and use the longer measurement. If you are between sizes, choose the larger size.</p></section>
    </div><aside className="space-y-4 lg:sticky lg:top-8 lg:self-start"><div className="bg-[#382820] p-6 text-[#FFFDF8]"><p className="eyebrow text-[#D7C2A7]">Need a second opinion?</p><h2 className="mt-3 font-display text-3xl">We can help with fit.</h2><p className="mt-3 text-sm leading-7 text-[#D7C2A7]">Share your measurements and the piece you are considering. Our team can help you compare the fit.</p><Link href="/contact" className="action-link-light mt-6 inline-flex items-center gap-2 bg-[#FFFDF8] px-5 py-4 text-[10px] uppercase tracking-[.15em] text-[#382820]">CONTACT US <ArrowRight size={14} /></Link></div><Link href="/faq" className="focus-ring flex items-center justify-between border border-[#D7C2A7] bg-[#FFFDF8]/60 p-4 text-[10px] uppercase tracking-[.13em] transition hover:border-[#B7654A] hover:text-[#B7654A]">VIEW FAQs <ArrowRight size={14} /></Link></aside></section>
  </main><BackToTop /><footer className="border-t border-[#D7C2A7] py-6"><div className="container flex flex-wrap items-center justify-between gap-3 text-xs text-[#866F62]"><span>{brand.name} · Fit, clearly considered</span><Link href="/shop" className="transition hover:text-[#B7654A]">Continue shopping <ArrowRight size={13} className="ml-1 inline" /></Link></div></footer></div>;
}
