import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { InsertUser, users, products, wishlists, wishlistItems, reviews } from "../drizzle/schema";
import { ENV } from './_core/env';
let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn('[Database] Failed to connect:', error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error('User openId is required for upsert'); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; const textFields = ['name','email','loginMethod'] as const; textFields.forEach(field => { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }); if (user.lastSignedIn !== undefined) { values.lastSignedIn = user.lastSignedIn; updateSet.lastSignedIn = user.lastSignedIn; } if (user.role !== undefined) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = 'admin'; updateSet.role = 'admin'; } if (!values.lastSignedIn) values.lastSignedIn = new Date(); if (!Object.keys(updateSet).length) updateSet.lastSignedIn = new Date(); await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function getPrimarySettings(userId: number) { const db = await getDb(); if (!db) return { primaryAddressId: null, primaryPaymentId: null }; const result = await db.select({ primaryAddressId: users.primaryAddressId, primaryPaymentId: users.primaryPaymentId }).from(users).where(eq(users.id, userId)).limit(1); return result[0] ?? { primaryAddressId: null, primaryPaymentId: null }; }
export async function updatePrimarySettings(userId: number, values: { primaryAddressId?: string | null; primaryPaymentId?: string | null }) { const db = await getDb(); if (!db) return getPrimarySettings(userId); await db.update(users).set(values).where(eq(users.id, userId)); return getPrimarySettings(userId); }
export async function listProducts() { const db = await getDb(); return db ? db.select().from(products).where(eq(products.status, 'active')) : []; }
export async function listWishlist(userId: number) { const db = await getDb(); if (!db) return []; const list = await db.select().from(wishlists).where(eq(wishlists.userId, userId)).limit(1); if (!list[0]) return []; return db.select().from(wishlistItems).where(eq(wishlistItems.wishlistId, list[0].id)); }
export async function listApprovedProductReviews(productId: number) { const db = await getDb(); if (!db) return []; return db.select({ id: reviews.id, rating: reviews.rating, body: reviews.body, verifiedPurchase: reviews.verifiedPurchase, createdAt: reviews.createdAt }).from(reviews).where(and(eq(reviews.productId, productId), eq(reviews.status, 'approved'))).orderBy(desc(reviews.createdAt)); }
